Repository eclipse-tractusx/digital-product-pass, pull requests merged in 2023-12, with the labels that each got.

#149 [ 1° ] - Release/v1.4.0 automate testdata registration: prepare and refactor shell scripts to automate testdata registration/deletion
  deployment/infrastructure/README.md
  deployment/infrastructure/delete-provider-dtr.sh
  deployment/infrastructure/delete-provider.sh
  deployment/infrastructure/init-provider-dtr-irs.sh
  deployment/infrastructure/init-provider-dtr.sh
  deployment/infrastructure/init-provider.sh
  deployment/infrastructure/resources/dpp/assets/IMR18650V1.json
  deployment/infrastructure/resources/dpp/assets/NCR186850B.json
  deployment/infrastructure/resources/dpp/assets/X123456789012X12345678901234566.json
  deployment/infrastructure/resources/dpp/assets/Y792927456954B81677903848654570.json
  deployment/infrastructure/resources/dpp/assets/digital-twin-registry.json
  deployment/infrastructure/resources/dpp/contractdefinitions/IMR18650V1.json
  deployment/infrastructure/resources/dpp/contractdefinitions/NCR186850B.json
  deployment/infrastructure/resources/dpp/contractdefinitions/X123456789012X12345678901234566.json
  deployment/infrastructure/resources/dpp/contractdefinitions/Y792927456954B81677903848654570.json
  deployment/infrastructure/resources/dpp/contractdefinitions/digital-twin-registry.json
  deployment/infrastructure/resources/dpp/contractpolicies/IMR18650V1.json
  deployment/infrastructure/resources/dpp/contractpolicies/NCR186850B.json
  deployment/infrastructure/resources/dpp/contractpolicies/X123456789012X12345678901234566.json
  deployment/infrastructure/resources/dpp/contractpolicies/Y792927456954B81677903848654570.json
  deployment/infrastructure/resources/dpp/contractpolicies/digital-twin-registry.json
  deployment/infrastructure/resources/dpp/digitaltwins/IMR18650V1.json
  deployment/infrastructure/resources/dpp/digitaltwins/NCR186850B.json
  deployment/infrastructure/resources/dpp/digitaltwins/X123456789012X12345678901234566.json
  deployment/infrastructure/resources/dpp/digitaltwins/Y792927456954B81677903848654570.json
  deployment/infrastructure/resources/irs/assets/DT-BAT-XYZ789.json
  deployment/infrastructure/resources/irs/assets/digital-twin-registry.json
  deployment/infrastructure/resources/irs/contractdefinitions/DT-BAT-XYZ789.json
  deployment/infrastructure/resources/irs/contractdefinitions/digital-twin-registry.json
  deployment/infrastructure/resources/irs/contractpolicies/DT-BAT-XYZ789.json
  deployment/infrastructure/resources/irs/contractpolicies/digital-twin-registry.json
  deployment/infrastructure/resources/irs/digitaltwins/DT-BAT-XYZ789+BOMAsBuilt.json
  deployment/infrastructure/resources/irs/digitaltwins/DT-CTA-13123+BOMAsBuilt.json
  deployment/infrastructure/resources/irs/digitaltwins/DT-EVMODULE-TRJ712+BOMAsBuilt.json
  deployment/infrastructure/testing/delete-testdata.sh
  deployment/infrastructure/testing/functions.sh
  deployment/infrastructure/testing/testdata/dpp/BAT-XYZ789.json
  deployment/infrastructure/testing/testdata/dpp/CTA-13123.json
  deployment/infrastructure/testing/testdata/dpp/EVMODULE-TRJ712.json
  deployment/infrastructure/testing/testdata/dpp/IMR18650V1.json
  deployment/infrastructure/testing/testdata/dpp/NCR186850B.json
  deployment/infrastructure/testing/testdata/dpp/SNJ-4654-76_payload.json
  deployment/infrastructure/testing/testdata/dpp/X123456789012X12345678901234566.json
  deployment/infrastructure/testing/testdata/dpp/Y792927456954B81677903848654570.json
  deployment/infrastructure/testing/testdata/dpp/singleLevelBomAsBuilt-BAT-XYZ789.json
  deployment/infrastructure/testing/testdata/dpp/singleLevelBomAsBuilt-CTA-13123.json
  deployment/infrastructure/testing/testdata/dpp/singleLevelBomAsBuilt-EVMODULE-TRJ712.json
  deployment/infrastructure/testing/testdata/dpp/singleLevelUsageAsBuilt-CTA-13123.json
  deployment/infrastructure/testing/testdata/dpp/singleLevelUsageAsBuilt-EVMODULE-TRJ712.json
  deployment/infrastructure/testing/testdata/smc/smc_asset.json
  deployment/infrastructure/testing/testdata/smc/smc_contract-definition.json
  deployment/infrastructure/testing/testdata/smc/smc_digital-twin.json
  deployment/infrastructure/testing/testdata/smc/smc_manual_payload.json
  deployment/infrastructure/testing/testdata/smc/smc_payload_partAsPlanned.json
  deployment/infrastructure/testing/testdata/smc/smc_policiy.json
  deployment/infrastructure/testing/testdata/testdata-payload.json
  deployment/infrastructure/testing/transform-and-upload.sh
  deployment/infrastructure/testing/upload-testdata.sh
  deployment/infrastructure/upload-smc-data.sh
Labels: edc-connector

#148 [ 3° ] - Release/v1.4.0 Bugfix/dtr lookup: Fixed bugs related to negotiation timeout and "gost" contract id
  CHANGELOG.md
  charts/digital-product-pass/templates/deployment-backend.yaml
  charts/digital-product-pass/values-beta.yaml
  charts/digital-product-pass/values-dev.yaml
  charts/digital-product-pass/values.yaml
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/config/DtrConfig.java
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/http/controllers/api/ContractController.java
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/managers/DtrSearchManager.java
  consumer-backend/productpass/src/main/java/utils/ThreadUtil.java
  consumer-backend/productpass/src/main/resources/application.yml
  docs/RELEASE_USER.md
Labels: bug

#156 [3º] - Release/v2.0.0 admin guide: Updated the admin guide
  docs/admin guide/Admin_Guide.md
Labels: documentation

#161 [7º] - Release/v2.0.0 authorization: Enabled BPN block and Role Authorization in the Digitla
  charts/digital-product-pass/Chart.yaml
  charts/digital-product-pass/README.md
  charts/digital-product-pass/templates/configmap-backend.yaml
  charts/digital-product-pass/templates/deployment-backend.yaml
  charts/digital-product-pass/templates/deployment-frontend.yaml
  charts/digital-product-pass/templates/secret-backend.yaml
  charts/digital-product-pass/values-beta.yaml
  charts/digital-product-pass/values-dev.yaml
  charts/digital-product-pass/values-int.yaml
  charts/digital-product-pass/values.yaml
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/config/SecurityConfig.java
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/listeners/AppListener.java
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/models/auth/UserInfo.java
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/services/AuthenticationService.java
  consumer-backend/productpass/src/main/java/utils/JsonUtil.java
  consumer-backend/productpass/src/main/resources/application.yml
  entrypoint.sh
  src/App.vue
  src/components/general/ErrorComponent.vue
  src/components/general/Footer.vue
  src/components/general/NotAuthorizedComponent.vue
  src/components/general/NotAvailableComponent.vue
  src/main.js
  src/media/Home.png
  src/services/Authentication.js
  src/services/service.const.js
  src/utils/authUtil.js
  src/utils/cryptUtil.js
  src/utils/jsonUtil.js
Labels: backend, security

#153 [ 11º ] - Feature/swaggerhub workflow: Prepared workflow to host backend API specs to the central swaggerhub
  .github/actions/setup-java/action.yaml
  .github/workflows/publish-swagger-hub.yaml
Labels: documentation

#165 chore: updated workflow to new packege path
  .github/workflows/publish-swagger-hub.yaml
Labels: bug

#167 fix: increased to 20 seconds swagger sleep
  .github/workflows/publish-swagger-hub.yaml
Labels: bug

#168 Hotfix/Release User: Updated the user release file
  docs/RELEASE_USER.md
Labels: bug

#169 chore: updated docker file backend
  dpp-backend/digitalproductpass/Dockerfile
Labels: bug
