Repository eclipse-tractusx/digital-product-pass, pull requests merged in 2023-08, with the labels that each got.

#98 [ 8º ] - release/v1.0.0 login bpn: Included the BPN number check of the connected EDC
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/listeners/AppListener.java
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/services/AuthenticationService.java
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/services/DataTransferService.java
  consumer-backend/productpass/src/main/java/utils/CatenaXUtil.java
  consumer-backend/productpass/src/main/java/utils/HttpUtil.java
  consumer-backend/productpass/src/main/resources/application.yml
Labels: backend

#99 [ 9º ] - release/v1.0.0 edc 5x: Added EDC v0.5.0 support and configuration
  DEPENDENCIES_BACKEND
  consumer-backend/productpass/pom.xml
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/http/controllers/AppController.java
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/managers/ProcessManager.java
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/models/edc/DataPlaneEndpoint.java
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/models/negotiation/Transfer.java
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/models/negotiation/TransferRequest.java
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/services/DataTransferService.java
  consumer-backend/productpass/src/main/java/utils/CrypUtil.java
  consumer-backend/productpass/src/main/java/utils/EdcUtil.java
  consumer-backend/productpass/src/main/java/utils/PassportUtil.java
  deployment/helm/edc-consumer/Chart.yaml
  deployment/helm/edc-consumer/values-beta.yaml
  deployment/helm/edc-consumer/values-int.yaml
  deployment/helm/edc-consumer/values.yaml
  deployment/helm/edc-provider/Chart.yaml
  deployment/helm/edc-provider/values-beta.yaml
  deployment/helm/edc-provider/values-int.yaml
  deployment/helm/edc-provider/values.yaml
Labels: edc-connector, backend

#100 [ 10° ] - Release/v1.0.0 postman helm: update postman to test registry APIs and modify helm templates
  charts/digital-product-pass/templates/deployment-frontend.yaml
  charts/digital-product-pass/templates/secret-frontend.yaml
  charts/digital-product-pass/values.yaml
  postman/v3.0.1/Digital-Product-Pass-collection.json
Labels: helm-charts

#101 [ 11º ] - Release/v1.0.0 contribution guidelines
  Branching_strategy.PNG
  CONTRIBUTING.md
Labels: documentation

#102 [ 12º ] - Release/v1.0.0 remove env charts
  charts/digital-product-pass/.helmignore
  charts/digital-product-pass/Chart.yaml
Labels: documentation

#103 [ 13º ] - Release/v1.0.0 search param: Added search param in the frontend
  src/services/BackendService.js
Labels: frontend

#112 [ 18° ] - Release/v1.0.0 technical deployment guide: Update technical deployment documentation
  deployment/README.md
  deployment/images/backend-logs.png
  deployment/images/battery-pass-electrochemical-properties.png
  deployment/images/battery-pass-general-information.png
  deployment/images/consumer-backend-logs.png
  deployment/images/consumer-frontend-logs.png
  deployment/images/create-app-with-plugin.png
  deployment/images/create-app-with-vault-plugin.png
  deployment/images/create-app.png
  deployment/images/dashboard.png
  deployment/images/electrochemical-properties.png
  deployment/images/frontend-logs.png
  deployment/images/general-information.png
  deployment/images/pod-sync.png
  deployment/images/pods.png
  deployment/images/running-pods.png
  deployment/images/scan-passport.png
  deployment/images/swagger.png
  deployment/images/sync-app.png
  deployment/images/sync-pod.png
Labels: documentation

#113 [ 19° ] - Release/v1.0.0 update documentation
  consumer-backend/productpass/docs/media/img2.png
  consumer-backend/productpass/readme.md
  deployment/helm/local/scripts/set_dev_values.sh
  deployment/helm/local/scripts/unset_dev_values.sh
  docs/GETTING-STARTED.md
  docs/SECRETS_MANAGEMENT.md
Labels: documentation

#114 [ 20° ] - Release/v1.0.0 end user manual: update end user documentation
  docs/user manual/MainMenu.png
  docs/user manual/User Manual Product Viewer App.md
  docs/user manual/scan-passport.png
Labels: documentation

#117 hotfix/v1.0.0-rc1-license: Added license in helm charts directory
  charts/digital-product-pass/LICENSE
Labels: helm-charts

#119 Release/v1.0.0-rc1-helm: Fixed bug related with frontend configuration + security vulnerabilities
  CHANGELOG.md
  DEPENDENCIES_BACKEND
  charts/digital-product-pass/Chart.yaml
  charts/digital-product-pass/values-beta.yaml
  charts/digital-product-pass/values-dev.yaml
  charts/digital-product-pass/values-int.yaml
  consumer-backend/productpass/pom.xml
  package-lock.json
  package.json
  src/services/service.const.js
Labels: bug, frontend, backend, helm-charts, dependencies

#120 Hotfix/v1.0.0-rc2: Updated Readme
  README.md
Labels: documentation

#121 Release/v1.0.0: Prepared release v1.0.0 + Release Documentation
  .github/workflows/sonar-scan.yaml
  CHANGELOG.md
  README.md
  charts/digital-product-pass/Chart.yaml
  charts/digital-product-pass/values.yaml
  docs/RELEASE_USER.md
  package-lock.json
  package.json
Labels: documentation, enhancement

#123 Hotfix/v1.0.0 rc3: Added security checks by default in chart
  CHANGELOG.md
  charts/digital-product-pass/Chart.yaml
  charts/digital-product-pass/README.md
  charts/digital-product-pass/values.yaml
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/http/controllers/AppController.java
  package-lock.json
  package.json
Labels: documentation, helm-charts

#124 Release v1.0.0: Prepared release 1.0.0 from release/1.0.0-rc3
  .github/workflows/helm-test.yaml
  charts/digital-product-pass/Chart.yaml
  package-lock.json
  package.json
Labels: documentation

#126 Release/v1.0.0- Prepared release v1.0.0 from release v1.0.0-rc4
  CHANGELOG.md
  charts/digital-product-pass/Chart.yaml
  package.json
Labels: helm-charts

#127 Hotfix/v1.0.0 docs trivy: add Notice in docs and fix trivy workflow
  .github/workflows/trivy.yml
  docs/GETTING-STARTED.md
  docs/IaC.md
  docs/RELEASE.md
  docs/RELEASE_USER.md
  docs/SECRETS_MANAGEMENT.md
  docs/admin guide/Admin_Guide.md
  docs/arc42/Arc42.md
  docs/business statement/Business Statement.md
  docs/cypress/CYPRESS.md
  docs/readme.md
  docs/user manual/User Manual Product Viewer App.md
Labels: documentation, workflows
