Repository eclipse-tractusx/digital-product-pass, pull requests merged in 2024-07, with the labels that each got.

#341 Feature/verification frontend: Adapt frontend to visualize the verification data
  DEPENDENCIES_FRONTEND
  dpp-frontend/package-lock.json
  dpp-frontend/src/assets/styles/components/general/dialog.scss
  dpp-frontend/src/assets/styles/components/general/passportHeader.scss
  dpp-frontend/src/assets/styles/main.scss
  dpp-frontend/src/components/general/Dialog.vue
  dpp-frontend/src/components/general/ErrorComponent.vue
  dpp-frontend/src/components/general/Footer.vue
  dpp-frontend/src/components/general/LoadingComponent.vue
  dpp-frontend/src/components/general/SearchInput.vue
  dpp-frontend/src/components/general/StepperItemFail.vue
  dpp-frontend/src/components/passport/PassportHeader.vue
  dpp-frontend/src/components/passport/sections/Specific.vue
  dpp-frontend/src/router/index.js
  dpp-frontend/src/services/Authentication.js
  dpp-frontend/src/services/BackendService.js
  dpp-frontend/src/services/service.const.js
  dpp-frontend/src/store/index.js
  dpp-frontend/src/translations/de.json
  dpp-frontend/src/translations/en.json
  dpp-frontend/src/utils/authUtil.js
  dpp-frontend/src/utils/configUtil.js
  dpp-frontend/src/utils/jsonUtil.js
  dpp-frontend/src/utils/passportUtil.js
  dpp-frontend/src/views/HomeView.vue
  dpp-frontend/src/views/PageNotFound.vue
  dpp-frontend/src/views/PassportView.vue
Labels: frontend, DPP Verification, add-on

#349 Chore/cleanup files: Removed unnecessary content/files and refactor workflows and helm charts
  .github/PULL_REQUEST_TEMPLATE.md
  .github/actions/run-dash/action.yaml
  .github/dependabot.yaml
  .github/workflows/codeql.yaml
  .github/workflows/eclipse-dash.yaml
  .github/workflows/eslint.yml
  .github/workflows/helm-test.yaml
  .github/workflows/helm-upgrade.yaml
  .github/workflows/kics.yml
  .github/workflows/publish-dpp-backend-docker-image.yml
  .github/workflows/publish-dpp-frontend-docker-image.yml
  .github/workflows/publish-swagger-hub.yaml
  .github/workflows/release-helm-charts.yml
  .github/workflows/trivy.yml
  charts/digital-product-pass/LICENSE
  charts/digital-product-pass/README.md
  charts/digital-product-pass/templates/deployment-backend.yaml
  charts/digital-product-pass/templates/deployment-frontend.yaml
  charts/digital-product-pass/templates/ingress-backend.yaml
  charts/digital-product-pass/templates/ingress-frontend.yaml
  charts/digital-product-pass/templates/pvc-data.yaml
  charts/digital-product-pass/templates/secret-backend.yaml
  charts/digital-product-pass/templates/service-backend.yaml
  charts/digital-product-pass/templates/service-frontend.yaml
  charts/digital-product-pass/values-int.yaml
  charts/digital-product-pass/values.yaml
  docs/admin/AdminGuide.md
  docs/architecture/Arc42.md
  docs/architecture/media/infrastructure/DeployementView.drawio.svg
  docs/architecture/media/infrastructure/GraphicArchitectureDiagram.drawio.svg
  docs/architecture/media/infrastructure/GraphicBackendComponent.drawio.svg
  docs/architecture/media/infrastructure/GraphicBlackboxOverallSys.drawio.svg
  docs/architecture/media/infrastructure/GraphicBulidingBlockView.drawio.svg
  docs/architecture/media/infrastructure/GraphicCrossCuttingConcepts.drawio.svg
  docs/architecture/media/infrastructure/GraphicFrontendComponent.drawio.svg
  docs/architecture/media/infrastructure/GraphicWhiteboxOverallSys.drawio.svg
  docs/architecture/media/intrastructure/DeployementView.drawio.svg
  docs/architecture/media/intrastructure/GraphicBlackboxOverallSys.drawio.svg
  docs/architecture/media/intrastructure/GraphicBulidingBlockView.drawio.svg
  docs/architecture/media/intrastructure/GraphicWhiteboxOverallSys.drawio.svg
  dpp-backend/charts/digital-product-pass-backend/.helmignore
  dpp-backend/charts/digital-product-pass-backend/Chart.yaml
  dpp-backend/charts/digital-product-pass-backend/LICENSE
  dpp-backend/charts/digital-product-pass-backend/README.md
  dpp-backend/charts/digital-product-pass-backend/templates/NOTES.txt
  dpp-backend/charts/digital-product-pass-backend/templates/_helpers.tpl
  dpp-backend/charts/digital-product-pass-backend/templates/configmap.yaml
  dpp-backend/charts/digital-product-pass-backend/templates/deployment.yaml
  dpp-backend/charts/digital-product-pass-backend/templates/ingress.yaml
  dpp-backend/charts/digital-product-pass-backend/templates/pvc-data.yaml
  dpp-backend/charts/digital-product-pass-backend/templates/secret.yaml
  dpp-backend/charts/digital-product-pass-backend/templates/service.yaml
  dpp-backend/charts/digital-product-pass-backend/templates/serviceaccount.yaml
  dpp-backend/charts/digital-product-pass-backend/templates/tests/test-connection.yaml
  dpp-backend/charts/digital-product-pass-backend/values-int.yaml
  dpp-backend/charts/digital-product-pass-backend/values.yaml
  dpp-backend/digitalproductpass/Dockerfile
  dpp-frontend/Dockerfile
Labels: documentation, helm-charts, docker, workflows

#375 chore(dtr): update dtr chart version to v0.5.0
  deployment/infrastructure/data-provider/registry/Chart.yaml
Labels: helm-charts

#382 Bugfix/edc policy: Fixed breaking changes in the backend
  docs/data-sovereignty/PolicyConfigGuide.md
  dpp-backend/digitalproductpass/src/main/java/org/eclipse/tractusx/digitalproductpass/core/models/negotiation/policy/Action.java
  dpp-backend/digitalproductpass/src/main/java/org/eclipse/tractusx/digitalproductpass/core/models/negotiation/policy/Constraint.java
  dpp-backend/digitalproductpass/src/main/java/org/eclipse/tractusx/digitalproductpass/core/models/negotiation/policy/LogicalConstraint.java
  dpp-backend/digitalproductpass/src/main/java/org/eclipse/tractusx/digitalproductpass/core/models/negotiation/request/TransferRequest.java
  dpp-backend/digitalproductpass/src/main/java/org/eclipse/tractusx/digitalproductpass/core/services/DataTransferService.java
  dpp-backend/digitalproductpass/src/main/resources/application.yml
  dpp-backend/digitalproductpass/src/test/java/managers/ProcessManagerTest.java
  dpp-backend/digitalproductpass/src/test/java/utils/PolicyUtilTest.java
  dpp-backend/digitalproductpass/src/test/resources/application-test.yml
  dpp-frontend/src/utils/edcUtil.js
Labels: bug, R24.08

#376 chore/frontend bug fix: Resolved issues to the frontend
  DEPENDENCIES_FRONTEND
  dpp-frontend/package-lock.json
  dpp-frontend/package.json
  dpp-frontend/src/components/passport/PassportHeader.vue
  dpp-frontend/src/components/passport/sections/Exchange.vue
  dpp-frontend/src/services/BackendService.js
  dpp-frontend/src/views/PassportView.vue
Labels: bug, R24.08

#386 release/v4.0.0 rc2/changelog: Release Preparation DPP v4.0.0
  CHANGELOG.md
  DEPENDENCIES_FRONTEND
  README.md
  charts/digital-product-pass/Chart.yaml
  charts/digital-product-pass/README.md
  charts/digital-product-pass/values.yaml
  deployment/infrastructure/data-consumer/edc-consumer/Chart.yaml
  deployment/infrastructure/data-consumer/edc-consumer/README.md
  deployment/infrastructure/data-provider/data-service/README.md
  deployment/infrastructure/data-provider/edc-provider/Chart.yaml
  deployment/infrastructure/data-provider/edc-provider/README.md
  deployment/infrastructure/data-provider/registry/README.md
  docs/RELEASE_USER.md
  dpp-frontend/package-lock.json
  dpp-frontend/package.json
  dpp-verification/README.md
Labels: R24.08

#388 chore: fix backend issues with policies and dsp endpoints/prepared v4.0.1
  CHANGELOG.md
  COMPATIBILITY_MATRIX.md
  README.md
  charts/digital-product-pass/Chart.yaml
  charts/digital-product-pass/README.md
  charts/digital-product-pass/templates/configmap-backend.yaml
  charts/digital-product-pass/templates/deployment-frontend.yaml
  charts/digital-product-pass/templates/ingress-frontend.yaml
  charts/digital-product-pass/templates/service-frontend.yaml
  charts/digital-product-pass/values-int.yaml
  charts/digital-product-pass/values.yaml
  docs/RELEASE_USER.md
  docs/interoperability/InteroperabilityGuide.md
  docs/media/dpp-tx-logo.png.license
  docs/media/passport-view.png
  docs/media/verification-addon.png
  dpp-backend/digitalproductpass/pom.xml
  dpp-backend/digitalproductpass/src/main/java/org/eclipse/tractusx/digitalproductpass/core/http/controllers/AppController.java
  dpp-backend/digitalproductpass/src/main/java/org/eclipse/tractusx/digitalproductpass/core/models/negotiation/request/TransferRequest.java
  dpp-backend/digitalproductpass/src/main/java/utils/CatenaXUtil.java
  dpp-backend/digitalproductpass/src/main/java/utils/HttpUtil.java
  dpp-backend/digitalproductpass/src/test/java/managers/ProcessManagerTest.java
  dpp-backend/digitalproductpass/src/test/java/services/DataTransferServiceTest.java
  dpp-backend/digitalproductpass/src/test/java/utils/CatenaXUtilTest.java
  dpp-frontend/package-lock.json
  dpp-frontend/package.json
  dpp-verification/README.md
  dpp-verification/charts/simple-wallet/values.yaml
  dpp-verification/resources/implementation/acr-document-credential.svg
  dpp-verification/resources/implementation/acr-document-credential.svg.license
  dpp-verification/resources/processes/acr-credential-resume.svg
  dpp-verification/resources/processes/acr-credential-resume.svg.license
  dpp-verification/resources/processes/acr-document-credential-resume.svg
  dpp-verification/resources/processes/acr-document-credential-resume.svg copy.license
  dpp-verification/schemas/acr/1.0.0/attributeCertificationRecord.jsonld
  dpp-verification/semantics/io.catenax.dpp_verification.acr/1.0.0/AttributeCertificationRecord.ttl
  dpp-verification/semantics/io.catenax.dpp_verification.acr/1.0.0/gen/AttributeCertificationRecord-Example-Expanded.jsonld
  dpp-verification/semantics/io.catenax.dpp_verification.acr/1.0.0/gen/AttributeCertificationRecord-Example.jsonld
  dpp-verification/semantics/io.catenax.dpp_verification.acr/1.0.0/gen/AttributeCertificationRecord-sample.json
  dpp-verification/semantics/io.catenax.dpp_verification.acr/1.0.0/gen/AttributeCertificationRecord-schema.json
Labels: backend, helm-charts, R24.08
