Repository eclipse-tractusx/digital-product-pass, pull requests merged in 2024-04, with the labels that each got.

#262 Release/v2.3.0 industry core changes: updated dpp testdata script and testdata payload
  CHANGELOG.md
  README.md
  deployment/local/testing/functions.sh
  deployment/local/testing/testdata/testdata-payload.json
  deployment/local/testing/transform-and-upload.sh
  dpp-backend/digitalproductpass/README.md
  src/assets/MOCK/SNJ-4654-76.json
  src/assets/MOCK/digitalProductPass-2.0.0.json
  src/assets/MOCK/dpp-materialPass-2.0.0.json
  src/assets/MOCK/gearDigitalProductPass-v2-refined.json
Labels: script

#280 ci: delete .github/workflows/veracode-upload.yml
  .github/workflows/veracode-pipeline.yml
Labels: security, action needed

#288 Bugfix/fix readme: Fixed table formatting in main README.md
  README.md
Labels: bug, documentation

#294 feat(dpp-verification): moving current draft from documentation from docs/verification
  .gitattributes
  dpp-verification/CC-BY-4.0
  dpp-verification/README.md
  dpp-verification/resources/processes/cdc-csc-workflow.svg
  dpp-verification/resources/processes/cdc-workflow.svg
  dpp-verification/resources/processes/csc-workflow.svg
  dpp-verification/resources/verification-logo.png
Labels: DPP Verification

#295 chore(swagger-bugfix): refactor workflow to resolve release version tag issue
  .github/workflows/publish-swagger-hub.yaml
  CHANGELOG.md
Labels: bug, workflows
